services:
  selenium:
    container_name: selenium
    image: talrozman/flight-management-system-web-scrapper:latest
    build: ./back/selenium
    ports:
      - "4444:4444"
    networks:
      - myApp

  server:
    container_name: django
    image: talrozman/flight-management-system-backend:latest
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    networks:
      - myApp

  front:
    container_name: react
    image: talrozman/flight-management-system-frontend:latest
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - myApp


networks:
  myApp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"